filter:
  excluded_paths:
  - tests/*

checks:
  php:
    code_rating: true
    duplication: true

tools:
  php_code_sniffer:
    config:
      standard: "WordPress"
  sensiolabs_security_checker: true
